### ISSUE TITLE
New feature suggestion: Create selection by master

### ISSUE THREAD

**Issue by Surrogate-TM** [nbelyh/vsu-releases#4]
Please add to Page related group feature: **create selection by master**.    
![VSU ribbon](https://sp-ao.shortpixel.ai/client/to_auto,q_lossless,ret_img/https://unmanagedvisio.com/wp-content/uploads/2023/08/image-1692578291887.png)
UserForm with combo-box which contain list with masters used at page. User select master name from list and all instances of this master selected.

**Comment by nbelyh** [comment]
In which tab/group do you think this could fit (above?)

**Comment by Surrogate-TM** [comment]
I think it would be better to put it in the **Page(s) group**

**Comment by nbelyh** [comment]
Resolved in 3.11

<img width="479" alt="image" src="https://github.com/user-attachments/assets/d3613848-6c57-466a-badf-0e440d82886e">

<img width="285" alt="image" src="https://github.com/user-attachments/assets/f3f42949-56c1-4dd4-a191-faf695041055">

**Comment by Surrogate-TM** [comment]
Thank you, Nikolay!
