### ISSUE TITLE
Copy/Move with Base Point

### ISSUE THREAD

**Issue by Surrogate-TM** [nbelyh/vsu-releases#5]
Please add your extension [Copy/Move with Base Point](https://unmanagedvisio.com/new-extension-copymove-with-base-point/)!
![Base Point Addin](https://sp-ao.shortpixel.ai/client/to_auto,q_lossless,ret_img/http://unmanagedvisio.com/wp-content/uploads/26-05-2013-13-36-50.png)     
It must placed in Shape(s) group…

**Comment by nbelyh** [comment]
That extension (BasePoint) is in C++...  Needs to be totally rewritten in C# to be integrated 🤔

**Comment by Surrogate-TM** [comment]
> That extension (BasePoint) is in C++

Oops !

**Comment by nbelyh** [comment]
Yep 😞 
Added a readme for that probject btw 😄

**Comment by Surrogate-TM** [comment]
https://visio.getbb.ru/viewtopic.php?f=6&t=138
a topic from 10 years ago can be useful :)

**Comment by nbelyh** [comment]
It's actually a total re-write of that add-in in C#...
It's possible, but I don't see much sense for it now. It is possible to simply install that old one. 
Closing for now 😅
