### ISSUE TITLE
Broken link for Order a License

### ISSUE THREAD

**Issue by davidjpp** [nbelyh/vsu-releases#6]
The https://unmanagedvisio.com/products/vsu/order dies not exist

**Comment by nbelyh** [comment]
Thank you David, on which page is this link?

**Comment by davidjpp** [comment]
On the About dialog

**Comment by nbelyh** [comment]
Ups. Added a redirect on the site.

**Comment by nbelyh** [comment]
Fixed on the server. Both links should work now. Thank you so much!
